# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 13:56
from __future__ import unicode_literals

import apps.myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[apps.myapp.models.validate_min_len], verbose_name='Name')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[apps.myapp.models.validate_zero_price], verbose_name='UnitPrice')),
            ],
        ),
    ]
